### ISSUE TITLE
[Create Profile] The text filter on currency field is not showing the correct results.

### ISSUE THREAD

**Issue by anil203** [PayvoHQ/wallet#791] opened 2022-01-13 11:10 UTC
While creating a new profile, when the user attempts to filter out currency based on the text search, the search results are not filtered. Instead they display all the available currencies.

Ideally when user enters "BT" in the currency field, the all the filtered results should contain "BT" in them.

Steps to reproduce:
1. Open Create Profile form.
2. In the Currency field, enter any search text.

We'll notice that the results displayed are not filtered based on the text entered previously in step 2.

Refer to the attached video for better understanding.

https://user-images.githubusercontent.com/10047242/149319601-8f0bc3f8-aa56-4911-bb9a-6955c0a213d9.mp4

**Comment by dated** [comment] 2022-01-13 19:15
I am unable to reproduce this behaviour.

![image](https://user-images.githubusercontent.com/6547002/149394599-4cddbbf9-4361-4340-8888-7d354967249f.png)

I think you're build is not up to date, judging by the autocomplete on the name input - can you retry with an uptodate version?

**Comment by anil203** [comment] 2022-01-14 06:04
Yes, I have latest repo configured. Cloned the master branch, fresh yesterday.

**Comment by alfonsobries** [comment] 2022-01-17 18:40
@dated @anil203 This issue should be fixed here https://github.com/PayvoHQ/wallet/pull/810

**Closed** 2022-01-18 05:24 UTC
Labels: web
